# -*- coding: utf-8 -*-
"""StudyTrack_AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15rzvLK36yyzZ7DvmjW2CPbV6gajjEsAd
"""

import os
os.listdir()

import pandas as pd

df = pd.read_csv("StudentPerformanceFactors (1).csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

df.columns

df.dtypes

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(df['Exam_Score'], kde=True)
plt.title("Exam Score Distribution")
plt.show()

sns.scatterplot(x=df['Hours_Studied'], y=df['Exam_Score'])
plt.title("Hours Studied vs Exam Score")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

numeric_df = df.select_dtypes(include=['int64', 'float64'])

sns.heatmap(numeric_df.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap (Numeric Features Only)")
plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Teacher_Quality'] = le.fit_transform(df['Teacher_Quality'].astype(str))
df['Parental_Education_Level'] = le.fit_transform(df['Parental_Education_Level'].astype(str))
df['Distance_from_Home'] = le.fit_transform(df['Distance_from_Home'].astype(str))

df.head()

df['Teacher_Quality'] = df['Teacher_Quality'].fillna(df['Teacher_Quality'].mean())
df['Parental_Education_Level'] = df['Parental_Education_Level'].fillna(df['Parental_Education_Level'].mean())
df['Distance_from_Home'] = df['Distance_from_Home'].fillna(df['Distance_from_Home'].mean())

from sklearn.preprocessing import LabelEncoder

# Identify categorical columns
categorical_cols = df.select_dtypes(include=['object']).columns

# Label Encode each categorical column
le = LabelEncoder()

for col in categorical_cols:
    df[col] = le.fit_transform(df[col].astype(str))

df.head()

from sklearn.model_selection import train_test_split

# Separate input features (X) and target (y)
X = df.drop("Exam_Score", axis=1)
y = df["Exam_Score"]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training set size:", X_train.shape)
print("Testing set size:", X_test.shape)

cluster_features = df[
    ['Hours_Studied', 'Attendance', 'Sleep_Hours',
     'Previous_Scores', 'Tutoring_Sessions', 'Physical_Activity']
]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaled_features = scaler.fit_transform(cluster_features)

from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

wcss = []
for k in range(1, 8):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_features)
    wcss.append(kmeans.inertia_)

plt.plot(range(1, 8), wcss, marker='o')
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.title("Elbow Method")
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(scaled_features)

df.groupby('Cluster').mean()

plt.scatter(
    scaled_features[:, 0], scaled_features[:, 1],
    c=df['Cluster'], cmap='viridis'
)
plt.xlabel("Hours Studied (scaled)")
plt.ylabel("Attendance (scaled)")
plt.title("Student Clusters")
plt.show()

print("\nCluster-wise Student Behavior Summary:\n")
print(df.groupby('Cluster')[
    ['Hours_Studied', 'Attendance', 'Sleep_Hours',
     'Previous_Scores', 'Tutoring_Sessions', 'Physical_Activity']
].mean())

def label_cluster(cluster_id):
    if cluster_id == 0:
        return "Needs Improvement"
    elif cluster_id == 1:
        return "Average Performer"
    else:
        return "High Performer"

df['Cluster_Label'] = df['Cluster'].apply(label_cluster)

print(df[['Cluster', 'Cluster_Label']].head())

def recommend_study_habits(cluster_label):
    if cluster_label == "Needs Improvement":
        return (
            "Increase daily study hours, improve attendance, "
            "follow a fixed study schedule, and revise basics regularly."
        )
    elif cluster_label == "Average Performer":
        return (
            "Maintain consistency, add weekly revision, "
            "practice mock tests, and manage time better."
        )
    else:
        return (
            "Focus on advanced topics, competitive exams, "
            "peer mentoring, and performance optimization."
        )

df['Recommendation'] = df['Cluster_Label'].apply(recommend_study_habits)

print(df[['Cluster_Label', 'Recommendation']].head())

import joblib

joblib.dump(kmeans, "studytrack_kmeans_model.pkl")
joblib.dump(scaler, "studytrack_scaler.pkl")

print("Model and scaler saved successfully!")

if __name__ == "__main__":
    print("StudyTrack AI clustering pipeline executed successfully.")

import os
os.listdir()



df.groupby('Cluster')[
    ['Hours_Studied','Attendance','Sleep_Hours',
     'Previous_Scores','Tutoring_Sessions','Physical_Activity']
].mean()

def recommend(cluster):
    if cluster == 0:
        return "Increase study hours, attendance, and regular revision."
    elif cluster == 1:
        return "Maintain consistency and improve weak subjects."
    else:
        return "Advanced preparation and competitive practice."

df[['Cluster']].head()
df['Recommendation'] = df['Cluster'].apply(recommend)
df[['Cluster','Recommendation']].head()

if __name__ == "__main__":
    print("StudyTrack AI clustering pipeline executed successfully.")
